### ISSUE TITLE
LAB-4 Поиск ассетов

### ISSUE THREAD

**Issue by aIbina** [aIbina/junior-hackathon-49#5]
- [ ] Спрайты
- [ ] Текстуры
- [ ] Шрифты
- [ ] Фон

**Comment by MariaShalunova** [comment]
![Image](https://github.com/aIbina/junior-hackathon-49/assets/60158598/61b70c86-aea8-42ef-a5ff-e4f01fc62ff9)

**Comment by MariaShalunova** [comment]
![Image](https://github.com/aIbina/junior-hackathon-49/assets/60158598/4684e92d-f9d8-4226-b66f-6e9f9719c3c6)
